# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('name', models.CharField(default='SOME STRING', max_length=140)),
                ('language', models.CharField(default='SOME STRING', max_length=140)),
                ('email', models.EmailField(default='SOME STRING', max_length=140)),
                ('sample_chapter', models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/$D/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
                ('favorite_fruit', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
